<?php
/**
 * Session
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bank Account APIs
 *
 * simulate the functionality of a basic bank account
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Session model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class Session 
{
        /**
     * session id
     *
     * @var string|null
     * @SerializedName("sessionId")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $sessionId;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->sessionId = isset($data['sessionId']) ? $data['sessionId'] : null;
    }

    /**
     * Gets sessionId.
     *
     * @return string|null
     */
    public function getSessionId()
    {
        return $this->sessionId;
    }

    /**
     * Sets sessionId.
     *
     * @param string|null $sessionId  session id
     *
     * @return $this
     */
    public function setSessionId($sessionId = null)
    {
        $this->sessionId = $sessionId;

        return $this;
    }
}


